services:
  eureka-service:
    build: eureka-service
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - gestionpacientes-network

  patient-service:
    build: patient-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - gestionpacientes-network
    depends_on:
      - eureka-service
      - config-server

  doctor-service:
    build: doctor-service
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - gestionpacientes-network
    depends_on:
      - eureka-service
      - config-server

  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    networks:
      - gestionpacientes-network
    depends_on:
      - eureka-service
      - config-server

  appointment-service:
    build: appointment-service
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - gestionpacientes-network
    depends_on:
      - eureka-service
      - config-server

  config-server:
    build: config-server
    mem_limit: 512m
    ports:
      - "8084:8084"
    networks:
      - gestionpacientes-network
    depends_on:
      - eureka-service

  
networks:
  gestionpacientes-network:
    driver: bridge