server:
  port: 8083

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# OpenFeign (si vas a comunicarte con otros servicios)
feign:
  client:
    config:
      default:
        loggerLevel: full

resilience4j:
  circuitbreaker:
    instances:
      doctorService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true



